# -*- coding: utf-8 -*-
"""Cyclic Conformal Cosmology Simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ER6V0PL1jySn5_3MSaYDja67KCGjACxF
"""

import numpy as np
import matplotlib.pyplot as plt

plt.style.use('dark_background')

"""Template for a single "lifetime" of a universe"""

class Aeon:
  def __init__(self, aeon_id, inital_size=0.01):
    self.aeon_id = aeon_id
    self.size = [inital_size]
    self.time = [0]

  def expand(self, steps=100, growth_rate=1.1):
    """Simulates the universe growing over time."""
    for t in range (1, steps):
      #The unverse grows exponentially
      new_size = self.size[-1] * growth_rate
      self.size.append(new_size)
      self.time.append(t)

"""Simulation for when the final state of one aeon become the next"""

def run_simulation(num_aeons=3):
  all_aeons = []
  current_start_size = 0.1

  for i in range(num_aeons):
    print(f"Starting Aeon {i}...")
    new_aeon = Aeon(aeon_id=i, inital_size=current_start_size)
    new_aeon.expand(steps=50) #Each universe will live for 50 'time units'
    all_aeons.append(new_aeon)

    #Now we do the jump
    #We will take the huge final size and then rescale it back to a tiny start
    current_start_size = 0.1 + (all_aeons[-1].size[-1]*0.00001)

  return all_aeons

"""Visualizing the infinite cylce"""

results = run_simulation(num_aeons=4)

plt.figure(figsize=(12, 6))
cumulative_time = 0

for aeon in results:
  #We shift the time so the aons appear one after another
  adjusted_time = np.array(aeon.time) + cumulative_time
  plt.plot(adjusted_time, aeon.size, label=f"Aeon {aeon.aeon_id}")
  cumulative_time += len(aeon.time)

plt.title("Confrontal Cyclic Cosmology")
plt.xlabel("Aeons")
plt.ylabel("Scale of the Universe")
plt.yscale('log')
plt.legend()
plt.show()

"""## 1. Objective
This project models the iInfinite Cycle theory of the universe. Instead of a linear timeline with a single beginning and end, this simulation explores the "Big Bounce" logic where the end of one universe resets into the start of another.

## 2. Theoretical Basis
* **Expansion:** Driven by Dark Energy, the universe stretches exponentially.
* **The Reset:** At the end of time, as matter decays into radiation (massless particles), the universe loses its sense of scale.
* **Conformal Transformation:** Mathematically, an infinitely large cold universe is identical to a tiny hot Big Bang.

## 3. Technical Implementation
* **Language:** Python
* **Key Libraries:** `NumPy` for math, `Matplotlib` for the "Heartbeat" graph.
* **Model Type:** State-based simulation using Object-Oriented Programming (OOP).
"""